# Dockerイメージを指定
FROM python:3.9.18
ENV PYTHONUNBUFFERED 1

# docker-compose.yml で指定した environment_name を設定
ARG environment_name
ENV environment=$environment_name

# ホストの作業ディレクトリをコンテナからマウント / 依存関係をインストール
WORKDIR /backend
COPY requirements.lock ./
RUN apt-get update \
    && apt-get install -y --no-install-recommends gettext \
    && apt-get install -y --no-install-recommends tree \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.lock


########## add on ##########
# GoogleCloud SDK
## GPGキーを設定 / Cloud SDK のインストール
## コンテナから gcloud auth application-default login 等使える
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    | tee /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
    && apt-get update \
    && apt-get install -y --no-install-recommends google-cloud-sdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

########## 立ち上げ ##########
COPY . .

ENV DJANGO_SUPERUSER_EMAIL="admin@admin.com"
ENV DJANGO_SUPERUSER_PASSWORD="defaultPwd123"

CMD ["/bin/sh", "-c", "\
    ./ProjectSetup.sh && \
    python manage.py createsuperuser --noinput || true && \
    tail -f /dev/null \
    "]