from .llm_settings import (
    MIN_TOKENS, MAX_TOKENS, SEND_MAX_TOKENS,
    RETRY_LIMIT_N, MAX_HISSTORY_N,
    MAX_LEN_SYSTEM_SENTENCE, MAX_LEN_ASSISTANT_SENTENCE,
    DEFAULT_ROOM_NAME, MAX_LEN_ROOM_NAME,
    ALLOWD_DOMAINS_LIST,
)
from .socket_settings import (
    SOCKET_REQUEST_PER_SEC_LIMIT,
    SOCKET_REXEIVE_DATA_KB_LIMIT,
)